twig_component:
    anonymous_template_directory: 'anonymous_components/'
    defaults:
        # Namespace & directory for components
        App\AssetComponents\: '%kernel.project_dir%/assets/components/'
